# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_coursenrollment_course_on_delete_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_field',
            field=models.TextField(default=False),
        ),
    ]
